name: flutter_image_compress
description: Compress image with native (Objective-C/Kotlin) with faster speed. Support Android/iOS.
version: 1.1.0
homepage: https://github.com/OpenFlutter/flutter_image_compress

environment:
  sdk: '>=2.10.5 <3.0.0'
  flutter: '>=2.0.0'


dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutterimagecompress
        pluginClass: FlutterImageCompressPlugin
      ios:
        pluginClass: FlutterImageCompressPlugin
